openapi: 3.0.0
info:
  title: Заказ ресурсов в облаке
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурса в облаке
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
           description: успешный ответ со списком ресурсов в облаке
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Clouds"
        "default":
           description: остальные ответы
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Error"
    post:
      summary: создаем заказ в облаке
      tags:
        - Clouds
      operationId: CreateCloud
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      responses:
        "200":
           description: успешное создание заказа в облаке
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Clouds"
        "default":
           description: остальные ответы
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Error"
  /clouds/{cloud_id}:
    delete:
      summary: Метод отмены заказа в облаке по ID
      tags: 
        - Clouds
      operationId: cancelCloudById
      parameters:
       - name: cloud_id
         in: path
         required: true
         description: идентификатор заказа в облаке
         schema:
           type: string
         example: f102b615
      responses:
        "200":
           description: успешное удаление заказа
           content:
             application/json: {}
        "404":
           description: Заказ с ID не найден
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Error"
        "default":
           description: Все остальное
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/Error"
    get:
      summary: Метод добавления заказа на облако по ID
      tags:
        - Clouds
      operationId: getCloudByIid
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f102b615
      responses:
        "200":
          description: Успешный ответ заказа облака по ID
          content:
            application/json: {}
        "404":
          description: Заказ с ID не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "default":
          description: Все остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - HDD
      properties:
        cloud_id:
          type: string
          example: f102b615
        id_client:
          type: string
          example: f102b615
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: Операционная система сервера
        RAM:
          type: string
          example: 128
          description: Объем оперативной памяти
        CPU:
          type: string
          example: 8
          description: Количество ядер процессора
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string